version: "3.8"
services:
  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminadmin

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-mongodb,grafana-mongodb-datasource
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

  mongodb_proxy:
    image: mongodb_proxy
    build: .
    container_name: mongodb_proxy
    restart: unless-stopped
    ports:
      - 3333:3333

volumes:
  grafana-storage:
